### ISSUE TITLE
The pretrained model is invalid

### ISSUE THREAD

**Issue by zhouchunpong** [imtiazziko/LaplacianShot#11]
Hi， Thank your for your code !

But I try to run the download_models.py and just get a 2KB ZIP.
Can you fix this bug or provide a googledrive Link ?

Thanks and Best !

**Comment by imtiazziko** [comment]
Hi @zhouchunpong 

Sorry that the link was not working. It's strange, and I am not sure why suddenly the file can not be accessed directly from the python download_models.py file.

However, I have updated the link now from where you can directly download the models from the Google Drive [here](https://drive.google.com/file/d/1SJdn8J8L9z6aCoHMQiPLU-Ol8QFoDECu/view?usp=sharing).

Please do not hesitate to contact if you have further questions.

Thanks

**Comment by pranay-ar** [comment]
@imtiazziko, even the latest link you shared is not working. Could you please update it?

**Comment by imtiazziko** [comment]
Hi @pranay-ar,  Thanks for pointing out. Updated it now. Should be fine.

**Comment by imtiazziko** [comment]
New link to the pretrained models [here](https://drive.google.com/file/d/1CG8ny7hD8i4GgjZN-Q1fU_i3smC4G6bG/view?usp=sharing).
