### ISSUE TITLE
can we remove ylog(y)?

### ISSUE THREAD

**Issue by amsword** [imtiazziko/LaplacianShot#2]
in Eqn. 4, it seems like we can remove y log(y). Based on Eqn. 6, Eqn. 4 will be upper bounded by a linear function of Y. Since each element of Y has to be 0 or 1, the optimal solution of teh upper bound could be easily solved by assigning the y whose linear coefficient is the smallest as 1, and all others as 0.

**Comment by imtiazziko** [comment]
Hi, Thanks for this good and interesting question.

Yeah, it could be done as well. However, in our case this negative log term is helping by implicitly handling the non-negativity constraints for simplex and duel variable for simplex constraints, which turns into a nice softmax update for each assignment. Also this term convexify the objectives which facilitates better optimization with better objective value.
