### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by Jiejiegary** [imtiazziko/LaplacianShot#4]
Thank you so much for the code!

Could you please provide your trained code once again since the link becomes invalid.

**Comment by imtiazziko** [comment]
Hi @Jiejiegary, I checked the trained model link is still ok. You just run the script [./src/download_models.py](https://github.com/imtiazziko/LaplacianShot/blob/master/src/download_models.py) and it will download the models for each configuration. And if you want to train the models. Just remove --evaluate from the script. That's it.

Thank you for your interest in the paper.

**Comment by Jiejiegary** [comment]
Great! thanks for your feedback.

**Comment by zhouchunpong** [comment]
> Great! thanks for your feedback.

@Jiejiegary 
Hi bro, have you got the pretrained model?  If have, could you share it with me ? 
Thank you so much!
